database:
  host: localhost
  nombre: test
  usuario: postgres
  pass: 1234
  puerto: 5434
  driver: postgresql

site:
  nombre: CandyUcab
  desc: Dulcería CandyUcab
  author: Grupo de Bases 1 UCAB
  url: localhost/candy-ucab/

framework:
  version: 1.0dev
  debug: false
